scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
     - targets: ['node-exporter:9100', 'domain.com:9111']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
     - targets: ['cadvisor:8080', 'domain.com:8888']
