version: "3.1"
services:
  node-exporter:
    image: prom/node-exporter:v1.0.1
    volumes:
      - /etc/hostname:/etc/nodename:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /mnt/docker-cluster:/mnt/docker-cluster:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/TZ:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9111:9100"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
    - 8888:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring
    depends_on:
    - redis
  redis:
    image: redis:latest
    networks:
      monitoring:
        aliases:
          - redis

networks:
  monitoring:

